### ISSUE TITLE
Xcode Versiyon Yönetim Uygulamasi

### ISSUE THREAD

**Issue by suatkarakusoglu** [suatkarakusoglu/mobilen#2]

**Comment by egehankalayci** [comment]
# Xcodes: Xcode'un Tüm Sürümlerini Keşfetmenin Yeni Yolu

Merhaba Mobilen okurları, bugün sizlere Xcode'un farklı sürümlerini nasıl kolaylıkla yönetebileceğinizi anlatacağım. 

![Image](https://github.com/suatkarakusoglu/mobilen/assets/36520043/221280ed-e5f4-455b-812b-6d6704139649)
Öncelikle, **Xcode**'un doğru yazımı konusunda bir anlaşma yapalım. İnsanlar bazen XCode, xCode gibi tuhaf kombinasyonlarla karşımıza çıkabilirler. Ancak gerçek şu ki, doğru yazımı **Xcode**'dur. Evet, büyük harfle "**X**" ile başlayıp ardından "**code**" olarak devam eder. Şimdi, bu konuda anlaştıysak **Xcode**'un farklı sürümlerini yönetme konusuna odaklanalım.

![Image](https://github.com/suatkarakusoglu/mobilen/assets/36520043/b8931d9f-d0d0-42e5-90a5-8206a293d8be)
Xcode, Apple platformlarında uygulama geliştirmek için kullanılan bir entegre geliştirme ortamıdır (IDE). Ancak, App Store'dan Xcode'u indirmenin bazı dezavantajları vardır. 
En güncel sürümleri bulmak veya yavaş bir indirme hızıyla karşılaşmakta sorun yaşayabilirsiniz. Daha da önemlisi, eski sürümlere geri dönmek veya birden fazla sürümü aynı anda kullanmak isterseniz, App Store bu özellikleri sunmamaktadır. 
![Image](https://github.com/suatkarakusoglu/mobilen/assets/36520043/d4089207-4958-406a-88df-e11dd4dbe5ec)
İşte tam da bu noktada size bir çözüm sunmak istiyorum: Xcodes!

Xcodes, Xcode'un farklı sürümlerini tek bir komutla indirmenizi sağlayan harika bir araçtır. Bu sayede istediğiniz sürümü, yüksek indirme hızlarıyla elde edebilirsiniz. 

Xcodes, indirme işlemlerini gerçekleştirmek için aria2 adlı bir komut satırı aracını kullanır. Bu araç, indirme hızınızı optimize etmek için çoklu bağlantılar ve paralel indirmeler kullanır. Böylece Xcode sürümlerini daha hızlı bir şekilde bilgisayarınıza indirebilirsiniz.

Gelelim Xcodes'u kullanmaya. Bunun iki farklı yöntemi bulunmaktadır. 
- İlk yöntem, Xcodes'un kullanıcı dostu bir arayüzü olan native uygulamasını indirip kullanmaktır. Bu sayede sürümleri görsel olarak kolaylıkla yönetebilirsiniz. 
![Image](https://github.com/suatkarakusoglu/mobilen/assets/36520043/37f3eb84-e51d-4c5e-ac3c-2c05bcb700ac)


- İkinci yöntem ise terminal üzerinden Xcodes'u kullanmaktır. Eğer terminal üzerinden kullanmak isterseniz, `xcodes` komutunu kullanarak çeşitli işlemleri gerçekleştirebilirsiniz. 
Örneğin, mevcut sürümleri görüntülemek için `xcodes list` komutunu kullanabilir, indirmek istediğiniz sürümün yanındaki numarayı yazarak indirme işlemini başlatabilirsiniz. Ayrıca, indirdiğiniz sürümleri `xcodes installed` komutu ile görüntüleyebilir ve `xcodes select` komutuyla varsayılan sürümü belirleyebilirsiniz.
![Image](https://github.com/suatkarakusoglu/mobilen/assets/36520043/bad0aa26-519a-4583-b8af-d5ef4af3ebda)


Artık Xcode'un farklı sürümlerini kolaylıkla yönetebilir, istediğiniz sürüme hızlıca erişebilir ve projelerinizde esnek bir şekilde çalışabilirsiniz.

Bir sonraki yazıda tekrar buluşmak dileğiyle.

## Kaynaklar
- https://www.xcodes.app/
- https://github.com/XcodesOrg
