### ISSUE TITLE
Pegasus'un Yükselişi: Apple, Google'a Meydan Okumaya Hazırlanıyor

### ISSUE THREAD

**Issue by guvennmehmet** [suatkarakusoglu/mobilen#22]
![google_apple](https://github.com/suatkarakusoglu/mobilen/assets/100021888/66ee03d7-cabf-4976-abe4-acfdbd84e51a)

Teknoloji devi Apple, arama motoru pazarında önemli bir hamle yaparak Google'ı ciddi bir rakip olarak hedefliyor. Apple, yıllık milyarlarca dolarlık bağımlılığını sonlandırmak amacıyla kendi arama motoru Pegasus’u geliştirmeye başladı. Pegasus, yapay zeka ve makine öğrenimi alanındaki uzmanlar tarafından geliştiriliyor.

Apple, Spotlight arama özelliğini geliştirerek, kullanıcılara web sonuçlarından uygulama detaylarına ve belgelere kadar birçok farklı içeriği Pegasus ile sunmayı hedefliyor. Pegasus, sadece iPhone'larla sınırlı kalmayacak; aynı zamanda App Store ve diğer uygulamalarda da kullanılacak. Pegasus ile birlikte, kullanıcılar istedikleri uygulamaları daha kolay bir şekilde bulabilecek. Apple, Pegasus ile reklam gelirlerini artırmayı hedefliyor.

Google, iPhone'ların varsayılan arama motoru olarak kalmak için yıllık milyarlarca dolar ödeme yapmaya devam ediyor. Ancak Apple'ın kendi arama motorunu geliştirmesi, bu anlaşmanın sona ermesine veya yeniden değerlendirilmesine yol açabilir. Ayrıca, Apple'ın reklam gelirlerini artırma potansiyeli, Google'ı olumsuz etkileyebilir.

Apple'ın Pegasus arama motorunun tam olarak ne zaman piyasaya sürüleceği henüz belirsizliğini koruyor. Apple'ın bu adımı ile teknoloji dünyasında büyük bir rekabetin başladığı görülüyor. Apple ve Google arasındaki arama motoru pazarındaki rekabet, kullanıcılara daha fazla seçenek sunabilir ve teknoloji dünyasında önemli bir değişim yaratabilir.

Sonuç olarak; Apple'ın Pegasus projesi, Google ile olan rekabeti daha da kızıştırabilir ve her iki şirketin stratejilerini ve rekabetini etkileyebilir.

Kaynakça:
- [Apple’s “Pegasus” search engine could pave the way for an in-house Google Search replacement](https://superchargednews.com/2023/10/01/apple-pegasus-search-google/)
- [Apple has a next-gen search engine called Pegasus, but don’t expect a Google Search competitor yet](https://9to5mac.com/2023/10/02/apple-pegasus-google-search/)

**Comment by suatkarakusoglu** [comment]
Eline sağlık, arama motorları tarafı LLM'ler ile de karıştı biraz Apple'da durmayacak gibi.
